[WIP] Actively Trigger Slow Path
dqian3/DOM-BFT pull request #48
Opened 2024-09-12 20:45 UTC by Hoooao

2024-09-13 17:12 UTC, Hoooao commented
I put the trigger in replicas, as they have the knowledge of global seq and altering digest is easy there.

2024-09-13 17:22 UTC, dqian3 requested changes

2024-09-13 17:22 UTC, dqian3 commented on processes/replica/replica.cc
> +        reply.set_digest(log_->getDigest() + replicaId_, SHA256_DIGEST_LENGTH);
Adding the replicaId here doesn't make sense to me? Since `getDigest` returns `byte *`, it does pointer arithmetic, which leads to undefined behavior.

If anything it should be concatenated then another digest could be created. Or you can just do something as simple as modifying the first/last byte.

I will also have to check to make sure that this is handled correctly in the slow path, I think the replicas just base their decisions off of the client id and seq, not the digests. This would result in replicas keeping their modified digests in the log.

2024-09-13 17:22 UTC, dqian3 commented on processes/replica/replica.cc
> +        reply.set_digest(log_->getDigest() + replicaId_, SHA256_DIGEST_LENGTH);
Nevermind about the last point, since it's only in the client replies

2024-09-14 02:57 UTC, Hoooao commented on processes/replica/replica.cc
> +        reply.set_digest(log_->getDigest() + replicaId_, SHA256_DIGEST_LENGTH);
updated so it changes the 1st byte

2024-09-14 21:45 UTC, dqian3 commented on lib/apps/counter.cc
> +    return std::string(reinterpret_cast<const char *>(&committed_state), INT_SIZE_IN_BYTES);
```suggestion
    return std::string(reinterpret_cast<const char *>(&committed_state.value), INT_SIZE_IN_BYTES);
```

2024-09-14 21:45 UTC, dqian3 commented on lib/log.cc
> +        prevDigest = log[(nextSeq - 1) % log.size()]->digest;
Please undo this change, it may look overcomplicated, but the problem is that if nextSeq is 0, then the way `%` works is that this would evaluate to `-1`, which is also undefined behavior.

2024-09-14 21:45 UTC, dqian3 commented on lib/log.cc
> +std::shared_ptr<LogEntry> * Log::getEntryPtr(uint32_t seq) {
This should just be a shared_ptr, not a pointer to a shared pointer

2024-09-14 21:45 UTC, dqian3 commented on lib/log.h
> +    std::shared_ptr<LogEntry> * getEntryPtr(uint32_t seq);
What is the point of this?

2024-09-14 21:45 UTC, dqian3 commented on processes/replica/replica.cc
> +void Replica::abortAppOpAndSyncWithLog(uint32_t startSeq) {
I don't understand this?

2024-09-14 21:45 UTC, dqian3 commented on processes/replica/replica.cc
> +        log_->commit(log_->checkpoint.seq);
This is a good spot, thanks for finding this.

2024-09-14 21:52 UTC, Hoooao commented on lib/log.cc
> +        prevDigest = log[(nextSeq - 1) % log.size()]->digest;
but nextSeq always init to 1, so i think it if fine

2024-09-14 21:53 UTC, Hoooao commented on lib/log.cc
> +std::shared_ptr<LogEntry> * Log::getEntryPtr(uint32_t seq) {
it is used as the iterator, as the iterator of array is just a double ptr.

2024-09-14 21:54 UTC, Hoooao commented on lib/log.h
> +    std::shared_ptr<LogEntry> * getEntryPtr(uint32_t seq);
same as above

2024-09-14 21:56 UTC, Hoooao commented on processes/replica/replica.cc
> +void Replica::abortAppOpAndSyncWithLog(uint32_t startSeq) {
it aborts the ops executed starting from startSeq. since we changed the log, we change the app's execution as well to make them consistent. So after aborting, the func iterate through the log to execute the new logs.

2024-09-14 21:57 UTC, Hoooao commented on lib/apps/counter.cc
> +    return std::string(reinterpret_cast<const char *>(&committed_state), INT_SIZE_IN_BYTES);
i think use the VersionedValue would be more valid as a snapshot.

2024-09-14 21:59 UTC, dqian3 commented on lib/apps/counter.cc
> +    return std::string(reinterpret_cast<const char *>(&committed_state), INT_SIZE_IN_BYTES);
yeah, but you only copy 4 (INT_SIZE_IN_BYTES). If you want to use the whole `VersionedValue`, you would need to serialize both parts individually.

2024-09-14 22:00 UTC, dqian3 commented on lib/log.cc
> +        prevDigest = log[(nextSeq - 1) % log.size()]->digest;
That's true, but having this function depend on that is not ideal imo

2024-09-14 22:01 UTC, dqian3 commented on processes/replica/replica.cc
> +void Replica::abortAppOpAndSyncWithLog(uint32_t startSeq) {
hmm, I think it would be good to refactor these out into some other class, it could be confusing to have this behavior for testing reordering be in the same place as the normal replica code.

2024-09-14 22:02 UTC, dqian3 commented on lib/log.cc
> +std::shared_ptr<LogEntry> * Log::getEntryPtr(uint32_t seq) {
Yes, but it is already a pointer, why not just pass the underlying shared_ptr?

2024-09-14 22:02 UTC, Hoooao commented on lib/apps/counter.cc
> +    return std::string(reinterpret_cast<const char *>(&committed_state), INT_SIZE_IN_BYTES);
changed to size of the struct

2024-09-14 22:03 UTC, dqian3 commented on lib/log.cc
> +std::shared_ptr<LogEntry> * Log::getEntryPtr(uint32_t seq) {
The only reason you would need the pointer to the shared ptr is if you want to fully overwrite the element at that point. You could just modify the entry, no?

2024-09-14 22:04 UTC, dqian3 commented on processes/replica/replica.cc
> +void Replica::abortAppOpAndSyncWithLog(uint32_t startSeq) {
For example, this should probably be in the log class. It would also be helpful with the slow path

2024-09-14 22:34 UTC, Hoooao commented on lib/log.cc
> +        prevDigest = log[(nextSeq - 1) % log.size()]->digest;
added an assert to check, as  nextSeq=0 is an error case.

2024-09-15 04:06 UTC, dqian3 commented on processes/replica/replica.cc
> +        std::srand(request.client_seq());
I think it would be more controllable to just deterministically swap two ops or not, based on replica id % 2 or something. This way we are certain that the fallback will trigger and don't have to worry about messing with the log so much.

2024-09-15 04:11 UTC, dqian3 commented
Ok, thinking about this a bit more, I think there is a bit of a gap between what I envisioned for this change and for what you envisioned. I think there's two purposes for this change:

1. To induce the slow path in a reliable manner, in order to see its affect on the overall performance of the protocol.
2. To induce the slow path in order to test it across different scenarios.

I think I was more focused on (1), and the changes here seem to be more oriented towards (2). For (1), we don't need to do anything random, we just need something consistent that will behave the same way each time it is called. For (2), I think this would be better served by unit tests. For example, generating 4 different logs, then running the fallback procedure on them and seeing a consistent result. I have some stuff setup for unit testing, but have not been good about implementing tests, so if that's something you are interested in that would be very helpful too!

2024-09-15 20:13 UTC, Hoooao commented
> Ok, thinking about this a bit more, I think there is a bit of a gap between what I envisioned for this change and for what you envisioned. I think there's two purposes for this change:
> 
> 1. To induce the slow path in a reliable manner, in order to see its affect on the overall performance of the protocol.
> 2. To induce the slow path in order to test it across different scenarios.
> 
> I think I was more focused on (1), and the changes here seem to be more oriented towards (2). For (1), we don't need to do anything random, we just need something consistent that will behave the same way each time it is called. For (2), I think this would be better served by unit tests. For example, generating 4 different logs, then running the fallback procedure on them and seeing a consistent result. I have some stuff setup for unit testing, but have not been good about implementing tests, so if that's something you are interested in that would be very helpful too!

For (1), I added a func to simply alter the digest to trigger slow path, which has basically no overhead. If we just want to have slow path, that one will be the most effective. 
I indeed thought the main purpose for swapping'd be like some regression test. But we can get rid of the rand to just swap the latest 2 logs.

2024-09-16 20:20 UTC, dqian3 reviewed
This `holdAndSwap` looks much simpler than what we have before, looks good. I left a few comments about the implementation though.

Also, if we're not using the swapLog and those APIs that you worked on, it would be better to not include them in the commit. They may come in handy in the future if we want to do some testing though, so it could be good to make a branch with these so we can reference them later.

2024-09-16 20:20 UTC, dqian3 commented on processes/replica/replica.h
> +    std::pair<std::optional<proto::ClientRequest>,std::optional<proto::ClientRequest>> heldRequests_;
Seems like we just need an optional, not a pair of optional, since you don't ever use the second one.

2024-09-16 20:20 UTC, dqian3 commented on processes/replica/replica.cc
> +    if(triggerFallbackFreq_ && replicaId_ % 2 && log_->nextSeq % triggerFallbackFreq_ == 0){
This should be `... % freq == 0` OR `... % freq == 1`, so that 2 adjacent requests are swapped. Otherwise, this would wait until the next time some request comes into be swapped. I guess it still kind of works though, cause the replica essentially drops a request.

2024-09-16 20:36 UTC, Hoooao commented on processes/replica/replica.h
> +    std::pair<std::optional<proto::ClientRequest>,std::optional<proto::ClientRequest>> heldRequests_;
the second one is used in the condition check that checks if the later req arrives. i don't want to introduce another member bool to record this, so simply made a pair of the same type.

2024-09-16 20:37 UTC, Hoooao commented on processes/replica/replica.cc
> +    if(triggerFallbackFreq_ && replicaId_ % 2 && log_->nextSeq % triggerFallbackFreq_ == 0){
the replica would not drop the req. the first req would be held, so the nextSeq does not get incremented. In this way, the next req arrived will still have `log_->nextSeq % triggerFallbackFreq_ == 0` to be true.

2024-09-16 20:38 UTC, dqian3 commented on processes/replica/replica.cc
> +        heldRequests_.second = request;
Here, you set the second member of the pair and immediately reset it though?

2024-09-16 20:41 UTC, dqian3 commented on processes/replica/replica.h
> +    std::pair<std::optional<proto::ClientRequest>,std::optional<proto::ClientRequest>> heldRequests_;
See https://github.com/dqian3/DOM-BFT/pull/48/files#r1761931810

2024-09-16 20:43 UTC, Hoooao commented on processes/replica/replica.cc
> +        heldRequests_.second = request;
`handleClientRequest` is recursively invoked

2024-09-16 21:01 UTC, dqian3 commented on processes/replica/replica.cc
> +    if(triggerFallbackFreq_ && replicaId_ % 2 && log_->nextSeq % triggerFallbackFreq_ == 0){
Yeah, that makes sense.

2024-09-16 21:03 UTC, dqian3 commented on processes/replica/replica.cc
> +    if(triggerFallbackFreq_ && replicaId_ % 2 && log_->nextSeq % triggerFallbackFreq_ == 0){
maybe add a comment to clarify this though, it's not obvious at first glance.

2024-09-18 06:36 UTC, dqian3 approved these changes

2024-09-18 06:36 UTC, dqian3 commented on processes/replica/replica.h
> +    void messReplyDigest(dombft::proto::Reply &reply);
```suggestion

```

2024-09-18 06:36 UTC, dqian3 commented on processes/replica/replica.cc
> +}
```suggestion
```

2024-09-18 06:39 UTC, dqian3 commented on lib/apps/counter.cc
> +    VersionedValue curSnapshot = *((VersionedValue *) snapshot.c_str());
You're right that this was not used correctly as you mentioned in the slack, but I think this doesn't solve it actually, it needs to be done at the Replica. Let's undo these changes for now and make this fix in another PR

2024-09-18 18:10 UTC, dqian3 approved these changes

2024-09-18 18:10 UTC, merged