[WIP] Fix Duplication and Missing in requests
dqian3/DOM-BFT pull request #67
Opened 2024-10-05 16:10 UTC by Hoooao

2024-10-07 17:18 UTC, Hoooao commented on processes/replica/replica.cc
> -        clientInstance_[clientId] = std::max(instance_, clientInstance_[clientId]);
originally the instance record was updated with the max between `instance_` and itself. but this is not effective as the latter can never be greater than `instance_` in the implementation.  And since the record is assigned as `instance_` here, the comparison in line 179 is always false so that it never sends back the blank reply.

Changed to comparing the instance in header and itself.

I am wondering if there is any action to be taken when it receives a req with a higher instance number compared to `instance_`?

2024-10-09 18:50 UTC, dqian3 approved these changes
Looks good! I'm assuming the `missSeq` is for future use?

2024-10-09 18:51 UTC, dqian3 commented
Actually, one issue is how this interacts with fallback. In fallback the state of each `ClientRecord` will change; that needs to be addressed before we merge this in, else we risk dropping requests by accident.

2024-10-09 18:53 UTC, dqian3 requested changes
see above comment about fallback.

2024-10-17 00:03 UTC, Hoooao commented on lib/fallback_utils.h
> +    const google::protobuf::RepeatedPtrField<dombft::proto::CheckpointClientRecord> *clientRecords;
I didn't want include `replica.h` in this file, so just used the proto one.

2024-10-17 00:20 UTC, Hoooao commented on processes/replica/replica.cc
> +        intermediateCheckpointClientRecords_ = clientRecords_;
we need an intermediate one since there will be inconsistency if there is a fallback happens before commit of the checkpoint. they are then essentially using the uncommited record as committed record and broadcast that with the proposal. During rollback, the `clientRecords_` will rollback to the in fact uncommitted record, and the checkpoint will rollback to the committed record: they are not consistent to each other.

2024-10-17 00:29 UTC, Hoooao commented on processes/replica/replica.h
> +    std::unordered_map<uint32_t , ClientRecord> checkpointClientRecords_;
refer to the previous cmt on `intermediateCheckpointClientRecords_ = clientRecords_`.

2024-10-17 00:30 UTC, Hoooao commented on lib/fallback_utils.cc
> -bool applySuffixToLog(const LogSuffix &logSuffix, std::shared_ptr<Log> log)
yeah, sometimes when the ide reports a warning i just let it autocorrect it lol.

2024-10-17 00:32 UTC, Hoooao commented on processes/replica/replica.cc
> -            assert(seq < log_->nextSeq);
`seq >=log_->nextSeq`  is impossible since the `seq` equals to   `checkpointCommits_[replicaId_].seq()`, where the latter is assigned by the replica itself. 
Did not notice the comments lol, but i guess it is unnecessary as the LOG below is more evident..

2024-10-26 19:53 UTC, dqian3 reviewed
Besides the inline comments, I had two other comments

1. Do you have the C++ formatter(clang format) setup in your environment? I noticed a few spots where it is inconsistent. The project has a file defining it so it should be pretty easy to setup.

2. Can `ClientRecord` be part of the log library? Might be a bit cleaner. The only reason I see it being a bit weird is becaue then to the replica, failing to add an entry to the log might be for multiple different reasons (duplicate client request or too much speculative history). But I think that could be handled properly.

3. Tests of the normal path fix would be helpful. For example to test for swaps, inserts, deletes, etc. That would be much better than trying to induce these, like you seem to have done.

2024-10-26 19:53 UTC, dqian3 commented on processes/receiver/receiver.cc
> +    // DEDUP TEST
Get rid of this before merging, or make this some runtime option like swapFreq

2024-10-26 19:53 UTC, dqian3 commented on lib/fallback_utils.cc
> +        // rollbackDone == true iff a mismatch is found
One way to make this cleaner: create an iterator for the entries in logSuffix.entry and make this a separate loop. Then we don't need to carry around this `rollbackDone` flag.

2024-10-26 19:53 UTC, dqian3 commented on lib/fallback_utils.cc
> -bool applySuffixToLog(const LogSuffix &logSuffix, std::shared_ptr<Log> log)
What was the compiler warning? I still don't see why this is needed.

2024-10-26 19:53 UTC, dqian3 commented on lib/fallback_utils.cc
> +        if(updateRecordWithSeq(clientRecords[clientId], clientSeq)){
For code readability, maybe do if not this, then some logic and `continue`. Also If `log->addEntry` fails, we need to undo this.

2024-10-26 19:53 UTC, dqian3 commented on lib/log.cc
> +// only shifts entries, no change in entry field
Please add a comment explaining what this does exactly in terms of the log. It's not easy to parse just looking at the code.

2024-10-26 19:53 UTC, dqian3 commented on lib/log.cc
> +    if (startSeq < nextSeq && (startSeq >= nextSeq - MAX_SPEC_HIST || startSeq < MAX_SPEC_HIST)) {
Let's make an `inRange` helper, this pattern pops up in a number of places.

2024-10-26 19:53 UTC, dqian3 commented on lib/log.cc
> +        for (uint32_t i = nextSeq - 1 + num; i - num >= startSeq; i--) {
This leave a gap in the entries, no?

2024-10-26 19:53 UTC, dqian3 commented on lib/client_record.h
> +    template <typename MessageType>
Why is this a template?

2024-10-26 19:53 UTC, dqian3 commented on lib/client_record.h
> +    template <typename MessageType>
Are there multiple message types where we need to do this?

2024-10-26 19:53 UTC, dqian3 commented on processes/replica/replica.cc
> +    if(curSeq != log_->nextSeq)
this only happens when we drop a message due to duplication?

2024-10-26 19:53 UTC, dqian3 commented on processes/replica/replica.cc
> +            // TODO(Hao): is providing these info enough for client?
There are two cases.
1. If the request is in our speculative history, then create a new reply with the same information
2. If the request has been committed in slow path or in the checkpoint protocol, we can treat this similar to a `fallback_executed` message. The client doesn't need to verify the digest or anything. It just needs to get `f + 1` consistent results.

2024-10-26 19:53 UTC, dqian3 commented on processes/replica/replica.cc
> +        log_->rightShiftEntries(startingSeq - rShiftNum,rShiftNum);
I think this right shift and then apply is a bit messy. It would probably just be cleaner to give this function a sequence number to start from (i.e. defining a suffix of the log), and then this function assumes it starts from the checkpoint. You would need to be careful about off-by-one errors though.

The easiest way to do this would be to copy the log into a separate vector (cheap because the log is already pointers to entries), and then just copy the entries into the appropriate places.

2024-10-26 19:53 UTC, dqian3 commented on proto/dombft_proto.proto
> +    repeated CheckpointClientRecord client_records = 7;
Could this be part of Checkpoint? Rearranging this would also make the ugly RepeatedPtrField thing go away most likely.

2024-10-26 22:26 UTC, Hoooao commented on lib/log.cc
> +        for (uint32_t i = nextSeq - 1 + num; i - num >= startSeq; i--) {
The gap will be in the range of the checkpoint

2024-10-26 22:34 UTC, Hoooao commented on lib/client_record.h
> +    template <typename MessageType>
yes it is also in fallbackstart. But we are not verifying the checkpoints during fallback, so i just didn't really verify the record at this point

2024-10-26 22:37 UTC, Hoooao commented on processes/replica/replica.cc
> +    if(curSeq != log_->nextSeq)
yes

2024-10-26 22:53 UTC, Hoooao commented on processes/replica/replica.cc
> +        log_->rightShiftEntries(startingSeq - rShiftNum,rShiftNum);
can you explain what you mean by "this function assumes it starts from the checkpoint"?

2024-10-27 03:52 UTC, dqian3 reviewed
Ok, I went and reviewed the main parts of the code as well, and also had two other thoughts.

1. We should refactor out some of the checkpoint stuff, as I've mentioned in other comments.

2. An easier way to search for the shift might just be to include which request `r` occurs at the checkpoint sequence number. Then the diverged replica can just search to find `r` in its log. Then we don't have to make a separate case for right or left shifts too.

2024-10-27 03:52 UTC, dqian3 commented on processes/replica/replica.cc
> +                int rShiftNum = getRightShiftNumWithRecords(checkpointClientRecords_,intermediateCheckpointClientRecords_);
Another random thought I had, here we should add a comment explaining the assumption that the replica waits until it has such a `intermediateCheckpointClientRecords_` (i.e. its log has reached this sequence number). This is a result of not processing reply/commit msgs until that point, but it isn't immediately obvious.

2024-10-27 03:52 UTC, dqian3 commented on processes/replica/replica.cc
> +                int rShiftNum = getRightShiftNumWithRecords(checkpointClientRecords_,intermediateCheckpointClientRecords_);
Actually, this assumption isn't true it seems? We skip the processing of `Reply` messages but not `Commit` messages, so this could happen.

2024-10-27 03:52 UTC, dqian3 commented on lib/client_record.h
> +    template <typename MessageType>
Can't you just create the protobuf object and set it directly instead of using a template? Like have it return a vector of clientRecords and copy each one in?

2024-10-27 03:52 UTC, dqian3 commented on lib/client_record.cc
> +            shiftNum += static_cast<int>(cliRecord2.missedSeqs_.size() - cliRecord1.missedSeqs_.size());
hmm, won't this first do unsigned substraction then cast to int? Seems like you could still get underflow.

2024-10-27 03:52 UTC, dqian3 commented on lib/client_record.cc
> +    int getRightShiftNumWithRecords(const ClientRecords &records1,const ClientRecords &records2)
So just to be clear, this is trying to find the amount each log shifted over by comparing the client records? So if clientRecord2 is behind by 1 request for a client or missing more requests than clientRecord2, then the rightshift number goes up?

2024-10-27 03:52 UTC, dqian3 commented on lib/client_record.cc
> +    int getRightShiftNumWithRecords(const ClientRecords &records1,const ClientRecords &records2)
This makes sense and I think it works, but it might be a bit overcomplicated.

2024-10-27 03:52 UTC, dqian3 commented on processes/replica/replica.cc
> +        log_->rightShiftEntries(startingSeq - rShiftNum,rShiftNum);
Like there is no case where we need to repply our entries from an arbitrary start sequence; we will always start from whatever the checkpoint is.

With this approach, you might be able to reuse the logSuffix stuff that is used in fallback as well, just a thought.

2024-10-27 22:10 UTC, Hoooao commented on lib/client_record.h
> +    template <typename MessageType>
yeah, but it is kind of messy i guess. and i wished to make it consistent wth the toProto func in Log class, where you give a reference of fallback_start msg, the log elements are then populated within the func.

2024-10-27 22:11 UTC, Hoooao commented on lib/fallback_utils.cc
> -bool applySuffixToLog(const LogSuffix &logSuffix, std::shared_ptr<Log> log)
was just an ide warning

2024-10-27 22:20 UTC, Hoooao commented on proto/dombft_proto.proto
> +    repeated CheckpointClientRecord client_records = 7;
do you mean the LogCheckpoint?

2024-10-27 22:23 UTC, Hoooao commented on lib/client_record.cc
> +    int getRightShiftNumWithRecords(const ClientRecords &records1,const ClientRecords &records2)
When replicas agree on a checkpoint, they agree on a record and the number of missing reqs as well, which essentially determines the # of shifts.

2024-10-27 22:33 UTC, Hoooao commented on lib/client_record.cc
> +            shiftNum += static_cast<int>(cliRecord2.missedSeqs_.size() - cliRecord1.missedSeqs_.size());
yes but the underflowed result will also be the correct negative value after casting it to int. but yeah should definitely cast them separately...

2024-10-27 22:45 UTC, Hoooao commented on processes/replica/replica.cc
> +                int rShiftNum = getRightShiftNumWithRecords(checkpointClientRecords_,intermediateCheckpointClientRecords_);
the `hasOwnCommit` makes sure that the current replica will wait till it handles the corresponding reply msg, by checking `checkpointCommits_[replicaId_].seq() == commit.seq()`. lmk if i misunderstood your scenario?

2024-10-27 22:56 UTC, Hoooao commented on processes/replica/replica.cc
> +                int rShiftNum = getRightShiftNumWithRecords(checkpointClientRecords_,intermediateCheckpointClientRecords_);
And simply searching for the req at the checkpoint sequence number would not work as that req can also be missed or gets delayed after the checkpoint.

2024-10-28 19:30 UTC, dqian3 commented on lib/fallback_utils.h
> +    const google::protobuf::RepeatedPtrField<dombft::proto::CheckpointClientRecord> *clientRecords;
Can't you just use the class in `client_record.h` then?

2024-10-28 19:32 UTC, dqian3 commented on lib/client_record.h
> +    template <typename MessageType>
Yeah, I think this is mostly right. The solution is probably to add a layer of indirection in the protobuf definitions. Make it so that a set of client records is itself a protobuf class, and then this problem is solved.

2024-10-28 19:32 UTC, dqian3 commented on proto/dombft_proto.proto
> +    repeated CheckpointClientRecord client_records = 7;
Yeah.

2024-10-28 19:34 UTC, dqian3 commented on processes/replica/replica.cc
> +                int rShiftNum = getRightShiftNumWithRecords(checkpointClientRecords_,intermediateCheckpointClientRecords_);
yeah, but if the request for the checkpoint `r` is missed or delayed, we can just give up. Like we discussed before, this is just an edge case, and would be fixed in the next checkpoint.

2024-10-28 19:35 UTC, dqian3 commented on lib/client_record.cc
> +            shiftNum += static_cast<int>(cliRecord2.missedSeqs_.size() - cliRecord1.missedSeqs_.size());
oh ok, I don't remember the specifics but that makes sense.

2024-10-28 20:32 UTC, Hoooao commented on proto/dombft_proto.proto
> +    repeated CheckpointClientRecord client_records = 7;
but we need it during checkpointing, but LogCheckpoint is only used in fallback no?

2024-10-28 21:28 UTC, Hoooao commented on lib/fallback_utils.cc
> +        if(updateRecordWithSeq(clientRecords[clientId], clientSeq)){
addEntry fails when `nextSeq > checkpoint.seq + MAX_SPEC_HIST` is true. But this is not possible in fallback as both the `checkpoint.seq` and the size of logSuffix.entries are determined by the applied logs from another replica in getting the suffix logic. 
I think we should rather have a more general handling of such case, like force a  checkpointing or something. 
Will add an inRange check before the record update anyway.

2024-10-29 20:08 UTC, dqian3 commented on processes/replica/replica.cc
> +    if (clientInstance < instance_) {
Maybe make the instance stuff separate?

2024-10-29 20:08 UTC, dqian3 commented on processes/replica/replica.cc
> +    if (rShiftNum) {
Do the same thing as right shift logic, copy into a new list first after removing duplicates, and apply in one go.

2024-10-31 00:05 UTC, Hoooao commented on processes/replica/replica.cc
> +            // TODO(Hao): is providing these info enough for client?
Since rn we dont have a mapping between req and info/entry, will add this logic later.

2024-11-01 21:21 UTC, dqian3 approved these changes

2024-11-01 21:21 UTC, merged